config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  get "/about" => "welcome#about", as: :about
  resources :users do
    resources :posts do
      resources :replies
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :replies, dependent: :destroy
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts, dependent: :destroy
         has_many :replies, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_posts_path(current_user)
  end

  # def after_update_path_for(resource)
  #   user_posts_path(current_user)
  # end
 protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :img, :school, :tel])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :location, :img, :school, :tel])
 end

 def after_update_path_for(resource)
   user_posts_path(current_user)
 end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, except: [:show]

  def index
    @user = current_user
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def new
    @user = current_user
    @post = @user.posts.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
     redirect_to user_posts_path(current_user)
    else
     render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:description, :title, :location, :help_time, :img, :notes, :user_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end












end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def index
    @replies = Reply.all
  end

  def show
    @reply = Reply.find(params[:id])
  end

  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @reply = @post.replies.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @reply = @post.replies.new(reply_params)
    @reply.user = @user

    if @reply.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def edit
    @replies = Reply.find(params{:id})
  end

  def update
    @reply = Reply.find(params[:id])

    if @reply.update_attributes(reply_params)
     redirect_to :replies
    else
     render :edit
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy
    redirect_to replies_path
  end
  private
  def reply_params
    params.require(:reply).permit(:content, :img, :user_id, :post_id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to :users
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
     redirect_to user_posts_path(@user)
    else
     render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :tel, :location, :img, :school)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockers</title>
    <link href='https://fonts.googleapis.com/css?family=Signika+Negative|Pathway+Gothic+One|Poiret+One|Yanone+Kaffeesatz|Montserrat' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </head>
  <nav class="navbar navbar-light" style="background-color: #ffffff;">
      <!-- <a class="navbar-brand" href="#">BLOCKERS</a> -->
      <%= link_to "BLOCKERS", root_path, :class => "navbar-brand" %>
      <ul class="nav navbar-nav">

        <li class="nav-item active">
          <%= link_to "Posts", user_posts_path(current_user), :class => "nav-link" unless current_user == nil %>
           <span class="sr-only">(current)</span>
        </li>

        <li class="nav-item active">
          <%= link_to "Post a Blocker", new_user_post_path(current_user), :class => "nav-link" unless current_user == nil %>
           <span class="sr-only">(current)</span>
        </li>

        <!-- <li class="nav-item">
       <a class="nav-link" href="#">Post a Blocker</a>
     </li> -->

         <li class="nav-item">
           <%= link_to "About", about_path, :class => "nav-link"  %>
         </li>
      </ul>

    <p align="right" id="user-nav">
  <% if user_signed_in? %>
    <span class="user_tag_color"> User:</span> <strong id="username"><%= current_user.name %></strong>.
    <%= link_to 'Edit profile', edit_user_path(current_user), :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
<% if notice %>
  <!-- <p class="alert alert-success"><%= notice %></p> -->
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</nav>

  <body>
    <% if controller_name == "welcome" %>
      <%= yield %>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Your Blocker!</h1>

<%= form_for [current_user, @post] do |f| %>

    <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>
    

    <div>
        <%= f.label :help_time %><br>
        <%= f.text_field :help_time %>
    </div>
    <div>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </div>
    <div>
        <%= f.hidden_field :user_id %>
    </div>


    <%= f.submit %>

<% end %>

<%#= link_to "Back to the Help list!", post_path %>

app/views/posts/index.html.erb
    <%# @posts.each do |post| %>
      <!-- <li> -->
        <!-- <strong>Title</strong> <%#= post.title %>  - <strong> Description:</strong> <%#= post.description %> - <strong> Area:</strong> - <%#= post.location %> - <%#= post.help_time %> - <strong> Image of Problem: </strong> <%#= post.img %> - <strong> School: </strong> <%#= post.user.school %> <br> -->

        <!-- <strong>replies:</strong>  <%#= post.replies.count %><br> -->

        <%#= link_to "More Info", user_post_path(@user, post) %><br>
      <!-- </li> -->
    <%# end %>
    <!-- <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-body"> -->

        <div class="panel-primary">
          <div class="panel-heading">
          <h2>Posts in your area</h2>
        </div>
        <div class="panel-body panel panel-default paddng">

          <ul>
          <% if @posts.where(location: @user.location).count == 0 %>
            <h3>Be the first to post a Blocker in this area!</h3>
          <% else %>
            <% @posts.where(location: @user.location).each do |post| %>
              <p> <strong> USER: </strong><%= post.user.name %> - <strong>TITLE</strong> : <%= post.title %>  -
                <strong> DESCRIPTION:</strong>
                <%= post.description %> -
                <strong> AREA:</strong> - <%= post.location %> -<STRONG> HELP TIME: <%= post.help_time %> -
                <strong> PIC OF BLOCKER: </strong> <%= post.img %> -
                <strong> SCHOOL: </strong> <%= post.user.school %> <br>
                <strong>REPLIES:</strong>  <%= post.replies.count %><br>
                <%= link_to "More Info", user_post_path(@user, post) %><br>
              </p>
            <% end %>
          <% end %>
        </ul>
      </div>
      </div>
    <!-- </div> -->




<div class="panel-primary">
  <div class="panel-heading">
<h2>Post a Blocker!</h2>
</div>
<div class="panel-body panel panel-default paddng">



<%= form_for [current_user, Post.new] do |f| %>

    <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>



    <div>
        <%= f.label :help_time %><br>
        <%= f.text_field :help_time %>
    </div>
    <div>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </div>
    <div>
        <%= f.label :notes %><br>
        <%= f.text_field :notes %>
    </div>

    <div>
        <%= f.hidden_field :user_id %>
    </div>

    <div class="col-md-6 post_blocker_button">
     <%= button_to "Post this Blocker", new_user_session_path, method: :get, class: "btn btn-info" %>
    </div>
  </div>
</div>
    <!-- <%#= f.submit "New Post!" %> -->

<% end %>

app/views/posts/new.html.erb
<div class="panel-primary">
  <div class="panel-heading">
<h3>Post a Blocker!</h3>
</div>
<div class="panel-body panel panel-default paddng">

<%= form_for [current_user, @post] do |f| %>

    <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>


    <div>
        <%= f.label :help_time %><br>
        <%= f.text_field :help_time %>
    </div>
    <div>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </div>
    <div>
        <%= f.label :notes %><br>
        <%= f.text_field :notes %>
    </div>

    <div>
        <%= f.hidden_field :user_id %>
    </div>

    <div class="col-md-6 post_blocker_button">
     <%= button_to "Post this Blocker", new_user_session_path, method: :get, class: "btn btn-info" %>
    </div>
    <!-- <%#= f.submit "New Post!" %> -->

  </div>
</div>
<% end %>

<%#= link_to "Back to the Help list!", post_path %>

app/views/posts/show.html.erb
<!-- <div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-body"> -->

    <div class="panel-primary">
      <div class="panel-heading">
<h2> <%= @post.title %> </h2>
</div>
<div class="panel-body panel panel-default paddng">

<p><h3> <%= @user.name %></h3> <strong>needs help with:</strong><br> <h4><%= @post.description %> </h4>NOTES:<h4><%= @post.notes %></h4> </p><br>
<% @post.replies.each do |reply| %>
  <strong> <%= reply.user.name %> said: </strong><h4> <%= reply.content %></h4><br> <strong> IMAGE OF SOLUTION?: </strong> <%= reply.img %><br>
<% end %><br>

<%= link_to "Break this Blocker", new_user_post_reply_path(@user, @post) %>&nbsp; &nbsp; &nbsp;
<%= link_to "Back to the Blocker list", user_posts_path(@user) %>&nbsp; &nbsp; &nbsp;
<% if current_user %>
  <% if current_user == @post.user %>
    <%= link_to "Edit post", edit_user_post_path(@user, @post) %>&nbsp; &nbsp; &nbsp;

  <% end %>

  <!-- the code below allows user to go to post page with a "get help button" made it dryer by comment out. -->
  <!-- <%= link_to "Get Help", new_user_post_path(@user) %> -->
<% end %>
    </div>
  </div>
</div>

app/views/replies/edit.html.erb
<h1>Edit User Profile</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :tel %>
        <%= f.text_field :tel %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>
    <div>
    <%= f.label :school %><br>
    <%= f.select(:school, ["General Assembly","Santa Monica High School", "New Roads High School", "Lincoln Middle School", "Crossroads School For Arts & Sciences","Roosevelt Elementary School","Brentwood School, East Campus","The Archer School for Girls","Paul Revere Charter Middle School","Brentwood School, West Campus","University High School","Venice High School","Palms Middle School"])  %>
      <%#= f.label :school %><br>
      <%#= f.text_field :school %>
    </div>

    <div>
        <%= f.label :img %>
        <%= f.text_field :img %>
    </div>

    <%= f.submit "Submit these changes!" %>

<% end %>

<%= link_to "Back to the list!", user_posts_path %>

app/views/replies/new.html.erb
<h1>Break a Blocker!</h1>

<%= form_for [@user, @post, @reply] do |f| %>

    <div>
        <%= f.label :content %><br>
        <%= f.text_field :content %><br>
    </div>

    <div>
        <%= f.label :img %><br>
        <%= f.text_field :img %><br>
    </div><br>



    <%= f.submit "Break this Block",class: "btn btn-info"  %>

<% end %><br>

<%= link_to "Back to the Blocker list!", user_posts_path(@user) %>

app/views/replies/show.html.erb
<!-- <h1> <%= @user.name %> </h1>
<p> This user <%= @user.name %> needs help with <%= @post.description %> </p>
<%= link_to "Edit this user profile", edit_user_path(@user) %>
<%= link_to "Back to the help list", users_path %>
<%= link_to "Delete this User Profile!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this user?"} %>
<%= link_to "Get Help", new_user_post_path(@user) %> -->

<!-- this code is not needed. -->

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :tel %><br>
        <%= f.text_field :tel %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>
    <div>
    <%= f.label :school %><br>
    <%= f.select(:school, ["General Assembly","Santa Monica High School", "New Roads High School", "Lincoln Middle School", "Crossroads School For Arts & Sciences","Roosevelt Elementary School","Brentwood School, East Campus","The Archer School for Girls","Paul Revere Charter Middle School","Brentwood School, West Campus","University High School","Venice High School","Palms Middle School"])  %>
      <%#= f.label :school %><br>
      <%#= f.text_field :school %>
    </div>

    <div>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </div>

    <div class="col-md-6 submit_edit_button">
     <%= button_to "Submit these changes", new_user_session_path, method: :get, class: "btn btn-info" %>
    </div>
    <%= link_to "Delete this User Profile!", user_registration_path, method: :delete, data: { confirm: "Are you sure you want to delete this user?"} %>
    <!-- <%#= f.submit "Submit these changes!" %> -->

<% end %>

app/views/users/index.html.erb
<!-- <h1>Users</h1>

<ul>
    <% @users.each do |user| %>
      <li>
        <strong> <%= user.name %> </strong> - <%= user.tel %> - <%= user.location %> - <%= user.img %> - <%= user.school %>
        <%= link_to "More Info",user_path(user) %>
      </li>
      <% end %>

</ul> -->

app/views/users/new.html.erb
<h1>Become a Helper!</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :tel %>
        <%= f.text_field :tel %>
    </div>

    <div>
    <%= f.label :location %><br>
    <%= f.select(:location, ["Santa Monica", "Brentwood", "West LA", "Venice", "Pacific Palisades"])  %>
        <!-- <%#= f.label :location %><br>
        <%#= f.text_field :location %> -->
    </div>
    <div>
    <%= f.label :school %><br>
    <%= f.select(:school, ["General Assembly","Santa Monica High School", "New Roads High School", "Lincoln Middle School", "Crossroads School For Arts & Sciences","Roosevelt Elementary School","Brentwood School, East Campus","The Archer School for Girls","Paul Revere Charter Middle School","Brentwood School, West Campus","University High School","Venice High School","Palms Middle School"])  %>
      <%#= f.label :school %><br>
      <%#= f.text_field :school %>
    </div>
    <div>
        <%= f.label :img %>
        <%= f.text_field :img %>
    </div>

    <%= f.submit "Sign up!" %>

<% end %>

<%= link_to "Back to the Help list!", users_path %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<p> This user <%= @user.name %> needs help with </p>
<%= link_to "Edit this user profile", edit_user_path(@user) %>
<%= link_to "Back to the help list", users_path %>
<%= link_to "Delete this User Profile!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this user?"} %>
<%= link_to "Get Help", new_user_post_path(@user) %>

app/views/welcome/about.html.erb
<div class="container about-header">
<div class="panel-primary">
  <div class="panel-heading">
<h1>About Blockers</h1>
</div>
<div class="panel-body panel panel-default paddng">
<h3>Ever wish you could get a quick answer to something that's Blocking you? Well now you can with BLOCKERS! Simply sign up and post your Blockers. Others from your community can quickly post the solution to why you are blocked. Its that simple!</h3>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron"  >
  <!-- <div class="imageandtext">
        <img class="monkeyimg" src="http://3.bp.blogspot.com/-Xik-tm4CH0M/T4_z4Ydo2xI/AAAAAAAAAL0/9XaZxgAOsIg/s1600/puzzled.png" class="center-block" alt="derry">
      <div class="ca"> -->

</div>
      <div class="caption">
        <p>BLOCKED!? Share what you need help with to get realtime feedback from your community.</p>
             Easily send solutions to what's blocking others or opt to meet up and collaborate on the problem.</p>
            <div class="col-md-6">
             <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "btn btn-info"%>
            </div>
            <div class="col-md-6">
             <%= button_to "Sign In", new_user_session_path, method: :get, class: "btn btn-info" %>
            </div>
        </p>
      </div>